In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [4]:
df = pd.read_csv('homeprices.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [7]:
import math
median_bedroom = math.floor(df['bedrooms'].median())
median_bedroom

4

In [10]:
df.bedrooms = df.bedrooms.fillna(median_bedroom)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [11]:
df.head

<bound method NDFrame.head of    area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000>

In [14]:
reg = linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']], df.price)

LinearRegression()

In [15]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [16]:
reg.intercept_

np.float64(221323.0018654043)

In [21]:
reg.predict([[3000,3,40]])

C:\Users\gurua\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

In [22]:
 112.06244194 * 3000 + 23388.88007794 * 3 + -3231.71790863 * 40 + 221323.0018654043

498408.2515740243

In [23]:
df2 = pd.read_csv('hiring.csv')
df2

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [26]:
df2['experience'] = df2['experience'].fillna('zero')

In [27]:
df2['experience']

0      zero
1      zero
2      five
3       two
4     seven
5     three
6       ten
7    eleven
Name: experience, dtype: object

In [30]:
pip install word2number

Note: you may need to restart the kernel to use updated packages.


In [35]:
from word2number import w2n

In [39]:
df2['experience'] = df2['experience'].apply(w2n.word_to_num)

In [40]:
df2['experience']

0     0
1     0
2     5
3     2
4     7
5     3
6    10
7    11
Name: experience, dtype: int64

In [41]:
df2

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [43]:
median = df2['test_score(out of 10)'].median()

In [52]:
df2['test_score(out of 10)'] = df2['test_score(out of 10)'].fillna(median)

In [46]:
reg2 = linear_model.LinearRegression

In [53]:
reg2 = linear_model.LinearRegression()
reg2.fit(df2[['experience','test_score(out of 10)','interview_score(out of 10)']], df2['salary($)'])

LinearRegression()

In [55]:
reg2.predict([[2,9,6]])

C:\Users\gurua\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53205.96797671])

In [56]:
reg2.predict([[12,10,10]])

C:\Users\gurua\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([92002.18340611])